services:
  server:
    container_name: "my_server"
    build: ./server
    networks:
      - my-network
    env_file:
      - config.env
  client:
    container_name: "my_client"
    depends_on:
      - server
    build: ./client
    networks:
      - my-network
    env_file:
      - config.env
networks:
  my-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "173.18.0.0/16"